//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToChange.DB_Connections
{
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ToChangeDBModelEntities : DbContext
    {
        public ToChangeDBModelEntities()
            : base("name=ToChangeDBModelEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Customer>().ToTable("Customer");
            modelBuilder.Entity<Exchange>().ToTable("Exchange");
            modelBuilder.Entity<Product>().ToTable("Product");
            modelBuilder.Entity<User>().ToTable("User");
            modelBuilder.Entity<Category>().ToTable("Category");
            modelBuilder.Entity<Poke>().ToTable("Poke");
            modelBuilder.Entity<SwapHandler>().ToTable("Swap");

        }

        public DbSet<Customer> Customers { set; get; }
        public DbSet<Exchange> Exchanges { set; get; }
        public DbSet<Product> Products { set; get; }
        public DbSet<User> Users { set; get; }
        public DbSet<Category> Categories { set; get; }
        public DbSet<Poke> Pokes { set; get; }
        public DbSet<SwapHandler> Swap { set; get; }
    }
}
